port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
proxies:
proxy-groups:
  - name: PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    proxies:
      - TEST-AKUN-SGP
      - TEST-AKUN-SG
      - TEST-AKUN
      - TEST-AKUN-IND
      - TEST-AKUN-ID
      - SERVER-SG
      - SERVER-ID
      - GAME-ONLY
  - name: TEST-AKUN-SGP
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - TEST-AKUN-SGP
  - name: TEST-AKUN-SG
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - TEST-AKUN-SG
  - name: TEST-AKUN
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - TEST-AKUN
  - name: TEST-AKUN-IND
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - TEST-AKUN-IND
  - name: TEST-AKUN-ID
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - TEST-AKUN-ID
  - name: SERVER-SG
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - SERVER-SG
  - name: SERVER-ID
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - SERVER-ID
  - name: GAME-ONLY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    use:
      - GAME-ONLY
proxy-providers:
  SERVER-ID:
    type: http
    path: "./proxy_provider/id.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/id.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  SERVER-SG:
    type: http
    path: "./proxy_provider/sg.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/sg.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  GAME-ONLY:
    type: http
    path: "./proxy_provider/game.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/game.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN:
    type: http
    path: "./proxy_provider/test.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-ID:
    type: http
    path: "./proxy_provider/test-id.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-id.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-IND:
    type: http
    path: "./proxy_provider/test-idn.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-idn.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-SG:
    type: http
    path: "./proxy_provider/test-sg.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-sg.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-SGP:
    type: http
    path: "./proxy_provider/test-sgp.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-sgp.yaml
    interval: 120
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - DOMAIN-SUFFIX,googlesyndication.com,PROXY
  - MATCH,PROXY
