---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - '8.8.8.8#📶SELECT-VPN📶'
  - '1.1.1.1#📶SELECT-VPN📶'
  - 180.131.144.144
  - 180.131.145.145
  - https://dns.google/dns-query
  - tls://dns.google
  default-nameserver:
  - '8.8.8.8#📶SELECT-VPN📶'
  - '1.1.1.1#📶SELECT-VPN📶'

proxy-providers:
  SERVER-ID:
    type: http
    path: "./proxy_provider/id.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/id.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  SERVER-SG:
    type: http
    path: "./proxy_provider/sg.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/sg.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  GAME-ONLY:
    type: http
    path: "./proxy_provider/game.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/game.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN:
    type: http
    path: "./proxy_provider/test.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-ID:
    type: http
    path: "./proxy_provider/test-id.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-id.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-IND:
    type: http
    path: "./proxy_provider/test-idn.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-idn.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-SG:
    type: http
    path: "./proxy_provider/test-sg.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-sg.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  TEST-AKUN-SGP:
    type: http
    path: "./proxy_provider/test-sgp.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/proxy_provider/test-sgp.yaml
    interval: 600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: 📶SELECT-VPN📶
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  proxies:
  - TEST-AKUN-ID
  - TEST-AKUN-IND
  - TEST-AKUN
  - TEST-AKUN-SG
  - TEST-AKUN-SGP
  - GAME-ONLY
  - SERVER-SG
  - SERVER-ID
- name: TEST-AKUN-SGP
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - TEST-AKUN-SGP
- name: TEST-AKUN-SG
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - TEST-AKUN-SG
- name: TEST-AKUN
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - TEST-AKUN
- name: TEST-AKUN-ID
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - TEST-AKUN-ID
- name: TEST-AKUN-IND
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - TEST-AKUN-IND
- name: GAME-ONLY
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - GAME-ONLY
- name: SERVER-SG
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - SERVER-SG
- name: SERVER-ID
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 300
  disable-udp: false
  use:
  - SERVER-ID
- name: 📱SOSMED📱
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - TEST-AKUN-SG
  - TEST-AKUN
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🎞STREAMING🎞
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - SERVER-ID
  - SERVER-SG
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🤖ABS🤖
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - TEST-AKUN-SGP
  - GAME-ONLY
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🇮🇩ID🇮🇩
  type: url-test
  disable-udp: false
  proxies:
  - TEST-AKUN-IND
  - TEST-AKUN-ID
  url: http://www.gstatic.com/generate_204
  interval: 300

rule-providers:
  rule_Direct:
    type: http
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/ABS.yaml
    interval: 86400
  rule_Indo:
    type: http
    behavior: classical
    path: "./rule_provider/rule_Indo.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/rule_indo.yaml
    interval: 86400
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/Sosmed.yaml
    interval: 86400
  rule_Streaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_streaming.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/Stream.yaml
    interval: 86400
  rule_Whatsapp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/whatsapp.yaml
    path: "./rule_provider/rule_Whatsapp.yaml"
    interval: 86400
  rule_lancidr:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/rule_lancidr.yaml
    path: "./rule_provider/rule_Whatsapp.yaml"
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/portgames.yaml
    interval: 86400
  rule_gametcp:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/Qerleng/Klompig/main/rule_provider/gametcp.yaml
    interval: 86400
    

rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN-SUFFIX,googlesyndication.com,📶SELECT-VPN📶
- RULE-SET,rule_portgames,DIRECT
- RULE-SET,rule_Direct,DIRECT
- RULE-SET,rule_gametcp,DIRECT
- RULE-SET,rule_lancidr,REJECT,no-resolve
- RULE-SET,rule_Sosmed,📱SOSMED📱
- RULE-SET,rule_Streaming,🎞STREAMING🎞
- RULE-SET,rule_Indo,🇮🇩ID🇮🇩
- RULE-SET,rule_Whatsapp,DIRECT
- MATCH,🤖ABS🤖

tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: false
# secret: '123456'
bind-address: "*"