name: Building binary files
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - master    

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building binary files
        run: chmod +x ./box/build.sh && bash build.sh
      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ github.token }}
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic update Rule Provider Clash
