name: Box Update

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building binary files
        run: |
          #更新UPX版本
          UPX_VER=$(curl -s https://api.github.com/repos/upx/upx/releases/latest |
              grep tag_name |
              cut -d ":" -f2 |
              sed 's/\"//g;s/\,//g;s/\ //g;s/v//' |
              head -n 1)

          curl -Lo upx.tar.xz "https://github.com/upx/upx/releases/download/v$UPX_VER/upx-$UPX_VER-amd64_linux.tar.xz"
          tar -xvf upx.tar.xz
          rm upx.tar.xz
          mkdir -p ./data/upx
          mv -f upx-$UPX_VER-amd64_linux/upx data/upx/
          rm -rf upx-$UPX_VER-amd64_linux/*

          #更新sing-box amd64核心和shellcrash arm64核心
          SINGBOX_VER=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases |
              grep '"prerelease": true,' -B 10 -m 1 |
              grep tag_name |
              cut -d ":" -f2 |
              sed 's/\"//g;s/\,//g;s/\ //g;s/v//')

          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v$SINGBOX_VER/sing-box-$SINGBOX_VER-linux-amd64.tar.gz"
          tar -zxvf sing-box.tar.gz -C sing-box
          rm sing-box.tar.gz
          mv -f sing-box/sing-box-$SINGBOX_VER-linux-amd64/sing-box sing-box/
          rm -rf sing-box/sing-box-$SINGBOX_VER-linux-amd64/*

          curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v$SINGBOX_VER/sing-box-$SINGBOX_VER-android-arm64.tar.gz"
          tar -zxvf sing-box.tar.gz -C sing-box/
          rm sing-box.tar.gz
          mv -f sing-box/sing-box-$SINGBOX_VER-linux-arm64/sing-box sing-box/CrashCore
          rm -rf sing-box/sing-box-$SINGBOX_VER-linux-arm64/*
          chmod +x data/upx/upx
          data/upx/upx --best sing-box/CrashCore
          cd sing-box
          tar -czvf CrashCore.tar.gz CrashCore
          rm CrashCore.tar.gz
          echo $SINGBOX_VER >README.md

      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ github.token }}
          debug: true
      - uses: snnaplab/delete-branch-cache-action@v1.0.0
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic Update Sing-Box

      
