name: Rule Provider

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tldextract pyyaml openpyxl
          
      - name: rule providers
        working-directory: ./rule_provider
        run: |
          echo "Downloading oisd full source list..."
          curl -sSf -o oisd-full.txt https://big.oisd.nl/
          python3 - <<EOF
          import re
          import yaml
          
          with open("oisd-full.txt", "r") as file:
              input_text = file.read()
          payload_lines = re.findall(r"\|\|(.+)\^", input_text)
          domains = []
          for line in payload_lines:
            if line:
              domain = line.split("$")[0].strip()
            if any(prefix in domain for prefix in ("autodesk", "github", "tiktok", "pinterest", "pinimg", "twitter", "linkedin", "telegram", "facebook", "line", "instagram", "whatsapp")):
              continue
            else:
                domains.append("DOMAIN-SUFFIX," + domain)

          payload = [f"{line}" for line in domains]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("rule_basicads.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm oisd-full.txt
          
          echo "Downloading oisd nsfw source list..."
          curl -sSf -o oisd-nsfw.txt https://nsfw.oisd.nl
          python3 - <<EOF
          import re
          import yaml
          
          with open("oisd-nsfw.txt", "r") as file:
              input_text = file.read()
          
          payload_lines = re.findall(r"\|\|(.+)\^", input_text)

          domains = []
          for line in payload_lines:
            if line:
              domain = line.split("$")[0].strip()
            if any(prefix in domain for prefix in ("autodesk", "github", "tiktok", "pinterest", "pinimg", "twitter", "linkedin", "telegram", "facebook", "line", "instagram", "whatsapp")):
              continue
            else:
                domains.append("DOMAIN-SUFFIX," + domain)

          payload = [f"{line}" for line in domains]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("rule_nsfw.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm oisd-nsfw.txt
          

          echo "Downloading Malicious Sites source list..."
          curl -sSf -o rule-malicious.txt https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_ABP.txt
          python3 - <<EOF
          import re
          import yaml
          
          with open("rule-malicious.txt", "r") as file:
              input_text = file.read()
          payload_lines = re.findall(r"\|\|(.+)\^", input_text)

          domains = []
          for line in payload_lines:
            if line:
              domain = line.split("$")[0].strip()
            if any(prefix in domain for prefix in ("autodesk", "github", "tiktok", "pinterest", "pinimg", "twitter", "linkedin", "telegram", "facebook", "line", "instagram", "whatsapp")):
              continue
            else:
                domains.append("DOMAIN-SUFFIX," + domain)

          payload = [f"{line}" for line in domains]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("rule_malicious.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm rule-malicious.txt

          echo "Downloading Malicious IP Addresses source list..."
          curl -sSf -o rule-maliciousip.txt https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_ipv4.txt
          python3 - <<EOF
          import re
          import yaml
          import ipaddress
          
          with open("rule-maliciousip.txt", "r") as file:
              input_text = file.read()
          payload_lines = re.findall(r"(.+)", input_text)
          domains = []
          ips = []
          for line in payload_lines:
            if line:
                if line[0].isdigit():
                    try:
                        ip = ipaddress.ip_network(line.strip().split('$')[0])
                        ips.append(ip.with_prefixlen)
                    except ValueError:
                        pass
                else:
                    domain = line.split("$")[0].strip()

                       
          rules = domains + ["IP-CIDR," + ip for ip in ips]
          payload = [f"{line}" for line in rules]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("rule_maliciousip.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm rule-maliciousip.txt

          echo "Downloading DOH IP Addresses source list..."
          curl -sSf -o rule-doh.txt https://raw.githubusercontent.com/malikshi/dns_ip/main/ip-dns.txt
          python3 - <<EOF
          import re
          import yaml
          import ipaddress
          
          with open("rule-doh.txt", "r") as file:
              input_text = file.read()
          payload_lines = re.findall(r"(.+)", input_text)
          domains = []
          ips = []
          for line in payload_lines:
            if line:
                if line[0].isdigit():
                    try:
                        ip = ipaddress.ip_network(line.strip().split('$')[0])
                        ips.append(ip.with_prefixlen)
                    except ValueError:
                        pass
                else:
                    domain = line.split("$")[0].strip()

                       
          rules = domains + ["IP-CIDR," + ip for ip in ips]
          payload = [f"{line}" for line in rules]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("rule_doh.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm rule-doh.txt
          
          echo "Downloading Personal_ads source list..."
          curl -sSf -o Personal_ads.txt https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt
          python3 - <<EOF
          import re
          import yaml
          
          with open("Personal_ads.txt", "r") as file:
              input_text = file.read()
          
          payload_lines = re.findall(r"0.0.0.0 (.+)", input_text)

          domains = []
          for line in payload_lines:
            if line:
              domain = line.split("$")[0].strip()
            if any(prefix in domain for prefix in ("autdsk", "gthub")):
              continue
            else:
                domains.append("DOMAIN," + domain)


          payload = [f"{line}" for line in domains]
          
          data = {
              "payload": payload
          }
          
          yaml_output = yaml.dump(data, sort_keys=False, default_flow_style=False)
          
          formatted_yaml = re.sub(r"(\s+-) '(.+)'", r"\1 \2", yaml_output)
          
          with open("Personal_ads.yaml", "w") as file:
              file.write(formatted_yaml)
          EOF
          rm Personal_ads.txt

          echo "Downloading Category-Porn source list..."
          curl -sSf https://raw.githubusercontent.com/zhihans/geodata/master/rule-set/geosite/geosite_category-porn.yaml -o rule_18+.yaml
          rm -fr rule_18+.yamle

          echo "Downloading Private source list..."
          curl -sSf https://raw.githubusercontent.com/zhihans/geodata/master/rule-set/geosite/geosite_private.yaml -o rule_privacy.yaml
          rm -fr rule_privacy.yamle
          
      - name: Run script convert rule provider
        run: python data/convert.py
      - name: move rule sing-box
        working-directory: ./sing-box
        run: |
          chmod +x sing-box
          for item in *.json; do
              ./sing-box rule-set compile "$item"
              mkdir -p ./rule_json/
              mkdir -p ./rule_srs/
              mv "${item%.json}.srs" rule_srs/
              mv "$item" rule_json/
          done
      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ github.token }}
          debug: true
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic update Rule Provider


          
