name:  MRS

on:
#  schedule:
#    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: move rule sing-box
        working-directory: ./sing-box
        run: |
          curl -Lo geoip.db "https://github.com/rfxcll/v2ray-rules-dat/releases/latest/download/GeoIP.db"
          curl -Lo geosite.db "https://github.com/rfxcll/v2ray-rules-dat/releases/latest/download/GeoSite.db"
          geoipAddresses=( "id" "facebook" "google" "netflix" "telegram" "twitter")
          geositeDomains=("oisd-full" "oisd-nsfw" "rule-ads" "oisd-small" "rule-doh" "rule-gaming" "rule-indo" "rule-playstore" "rule-sosmed" "rule-streaming" "rule-umum" "rule-ipcheck" "rule-speedtest" "videoconference" "rule-malicious" "urltest" "openai" "ecommerce-id")

          chmod +x sing-box
          for item in "${geoipAddresses[@]}"; do
              ./sing-box geoip export "$item"
          done
          for item in "${geositeDomains[@]}"; do
              ./sing-box geosite export "$item"
          done
              mkdir -p ./rule_ip/
              mkdir -p ./rule_srs/
              mv "$item" rule_ip/
          done
          rm -rf geoip.db geosite.db 
        
#      - name: converter mrs
#        working-directory: ./rule_provider
#        run: |
#          chmod 755 mihomo
#          for item in *.yaml; do
#              ./mihomo convert-ruleset domain yaml "$item" "${item%.yaml}.mrs"
#              mkdir -p ./rule_yaml/
#              mkdir -p ./rule_mrs/
#              mv "${item%.yaml}.mrs" rule_mrs/
#          done

      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ github.token }}
          debug: true
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic update Rule Provider
