
name: Update proxy

on:
  schedule:
    - cron: '0 1,13 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Show python version
        run: python --version
      - name: Run script update proxy
        run: python backup/gatcha/get-update-gatcha.py
#             python backup/proxy_provider/fool-provider.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
