name: test

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tldextract pyyaml openpyxl
          
      - name: Tese
        working-directory: ./rule_provider
        run: |
          echo "Downloading oisd full source list..."
          curl -sSf -o oisd-full.txt https://raw.githubusercontent.com/Qerleng/00/main/rule_provider/TEST.yaml
          curl -sSf -o oisd-full1.txt https://raw.githubusercontent.com/Qerleng/00/main/rule_provider/portgames.yaml
          python3 - <<EOF
          import re
          import yaml
          
          with open('oisd-full.txt') as f1, open('oisd-full1.txt') as f2:
            file1_lines = (f1.read().splitlines())
            file2_lines = (f2.read().splitlines())
          
          for line in file1_lines:
            if line in file2_lines:
              file1_lines.remove(line)
          
          with open('Removed.txt', 'w') as f3:
            f3.write("\n".join(file1_lines))
          EOF
          rm oisd-full.txt
          rm oisd-full1.txt


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update Rule Provider Clash
